# Batch Processing Configuration

# General Batch Settings
batch_processing:
  enabled: true
  default_batch_size: 10
  max_batch_size: 50
  min_batch_size: 1

# Concurrency Control
concurrency:
  max_concurrent_batches: 3
  max_concurrent_tasks: 15
  task_semaphore_limit: 10

  # Worker settings
  worker_pool_size: 8
  max_worker_tasks: 100
  worker_timeout: 300  # 5 minutes

# Queue Management
queue:
  max_queue_size: 1000
  priority_levels: 4
  queue_timeout: 3600  # 1 hour

  # Priority handling
  priority_boost_interval: 300  # 5 minutes
  starvation_prevention: true
  fair_sharing_enabled: true

# Rate Limiting
rate_limiting:
  enabled: true
  requests_per_second: 10
  requests_per_minute: 600
  burst_limit: 50

  # Adaptive rate limiting
  enable_adaptive_rate_limiting: true
  rate_limit_backoff_factor: 0.5
  rate_limit_recovery_factor: 1.1

# Retry Mechanism
retry:
  enabled: true
  max_attempts: 3
  base_delay: 1.0
  max_delay: 60.0
  backoff_multiplier: 2.0

  # Retry conditions
  retry_on_timeout: true
  retry_on_error: true
  retry_on_rate_limit: true
  retry_on_network_error: true

  # Exponential backoff
  enable_exponential_backoff: true
  jitter_enabled: true
  jitter_factor: 0.1

# Memory Management
memory:
  max_memory_usage: 2147483648  # 2GB
  memory_threshold: 0.8
  garbage_collection_interval: 300  # 5 minutes

  # Memory monitoring
  enable_memory_monitoring: true
  memory_check_interval: 60  # seconds
  memory_warning_threshold: 0.7

  # Memory optimization
  enable_memory_pooling: true
  pool_initial_size: 10
  pool_max_size: 50

# Performance Optimization
performance:
  enable_parallel_processing: true
  chunk_size: 5
  prefetch_enabled: true
  prefetch_count: 3

  # Caching
  enable_batch_caching: true
  cache_batch_results: true
  cache_ttl: 1800  # 30 minutes

  # Optimization strategies
  enable_adaptive_chunking: true
  enable_load_balancing: true
  enable_connection_pooling: true

# Error Handling
error_handling:
  enabled: true
  continue_on_error: true
  max_error_rate: 0.1  # 10%
  error_log_enabled: true
  error_notification_enabled: false

  # Error types to handle
  handle_timeouts: true
  handle_network_errors: true
  handle_rate_limits: true
  handle_validation_errors: true

  # Fallback strategies
  enable_fallback_mechanisms: true
  fallback_to_sequential: true
  fallback_to_smaller_batches: true

# Progress Tracking
progress_tracking:
  enabled: true
  progress_update_interval: 5  # seconds
  detailed_progress_enabled: true
  eta_calculation_enabled: true

  # Progress reporting
  report_intermediate_results: true
  report_completion_stats: true
  report_performance_metrics: true

# Monitoring and Metrics
monitoring:
  enabled: true
  metrics_collection_interval: 60  # seconds
  health_check_interval: 30  # seconds

  # Metrics to collect
  collect_performance_metrics: true
  collect_error_metrics: true
  collect_resource_metrics: true
  collect_business_metrics: true

  # Alerting
  alerting_enabled: false
  alert_thresholds:
    error_rate: 0.2  # 20%
    processing_time: 300  # 5 minutes
    memory_usage: 0.9  # 90%
    queue_size: 800

# Resource Management
resources:
  cpu_limit: 0.8  # 80% of available CPU
  memory_limit: 0.8  # 80% of available memory
  disk_space_limit: 0.9  # 90% of available disk

  # Resource monitoring
  enable_resource_monitoring: true
  resource_check_interval: 60  # seconds

  # Scaling
  enable_auto_scaling: false
  scale_up_threshold: 0.8
  scale_down_threshold: 0.3

# Batch Strategies
strategies:
  # Sequential processing
  sequential:
    enabled: true
    max_batch_size: 20
    timeout: 600  # 10 minutes

  # Parallel processing
  parallel:
    enabled: true
    max_workers: 8
    chunk_size: 5
    timeout: 300  # 5 minutes

  # Queue-based processing
  queue_based:
    enabled: true
    queue_size: 1000
    worker_count: 4
    timeout: 1800  # 30 minutes

  # Adaptive processing
  adaptive:
    enabled: true
    initial_batch_size: 10
    adjustment_interval: 60  # seconds
    performance_threshold: 0.8

# Task Prioritization
prioritization:
  enabled: true
  priority_levels:
    critical:
      weight: 1
      max_queue_time: 60  # 1 minute
    high:
      weight: 2
      max_queue_time: 300  # 5 minutes
    normal:
      weight: 3
      max_queue_time: 600  # 10 minutes
    low:
      weight: 4
      max_queue_time: 1800  # 30 minutes

  # Priority adjustment
  enable_priority_boost: true
  priority_boost_interval: 300  # 5 minutes
  max_priority_boost: 3

# Cleanup and Maintenance
cleanup:
  enabled: true
  cleanup_interval: 3600  # 1 hour
  retain_completed_jobs: 86400  # 24 hours
  retain_failed_jobs: 604800  # 7 days

  # Cleanup tasks
  cleanup_old_jobs: true
  cleanup_temp_files: true
  cleanup_memory_cache: true
  cleanup_disk_cache: true

# Logging and Auditing
logging:
  enabled: true
  log_level: "INFO"
  log_batch_operations: true
  log_individual_tasks: false
  log_performance_metrics: true

  # Log retention
  log_retention_days: 30
  max_log_size: 10485760  # 10MB
  log_rotation_enabled: true

  # Audit logging
  audit_enabled: true
  audit_log_file: "batch_audit.log"
  audit_retention_days: 90

# Configuration Validation
validation:
  enabled: true
  validate_on_startup: true
  validate_before_processing: true

  # Validation rules
  max_content_length: 10000
  min_content_length: 50
  allowed_file_types: [".txt", ".json", ".csv"]
  max_file_size: 10485760  # 10MB

  # Validation actions
  skip_invalid_items: true
  log_validation_errors: true
  quarantine_invalid_items: false