# 去重引擎配置

# 基础去重设置
similarity_threshold: 0.85    # 文本相似度阈值
semantic_threshold: 0.75      # 语义相似度阈值
cross_source_detection: true  # 跨源检测
time_window_hours: 24        # 时间窗口（小时）

# 指纹生成配置
fingerprinting:
  algorithm: sha256           # 哈希算法
  content_hash_length: 64    # 内容哈希长度
  semantic_hash_length: 64   # 语义哈希长度
  source_hash_length: 32     # 源哈希长度
  enable_normalize_content: true # 启用内容标准化

# 缓存配置
cache:
  enabled: true              # 启用缓存
  max_size: 10000            # 最大缓存大小
  ttl_hours: 24              # 缓存TTL（小时）
  cleanup_interval_hours: 1  # 清理间隔（小时）
  enable_persistence: false  # 启用持久化
  persistence_path: cache/deduplication_cache.json # 持久化路径

# 语义分析配置
semantic_analysis:
  enabled: true              # 启用语义分析
  vectorizer_type: tfidf     # 向量化器类型
  max_features: 1000         # 最大特征数
  ngram_range: [1, 3]       # N-gram范围
  use_svd: true             # 使用SVD降维
  svd_components: 100       # SVD组件数
  similarity_metric: cosine # 相似度度量

# 相似度计算权重
similarity_weights:
  content_similarity: 0.5    # 内容相似度权重
  title_similarity: 0.3      # 标题相似度权重
  semantic_similarity: 0.2   # 语义相似度权重

# 高级去重策略
advanced_strategies:
  enable_fuzzy_matching: true # 启用模糊匹配
  fuzzy_threshold: 0.8       # 模糊匹配阈值
  enable_time_decay: true    # 启用时间衰减
  decay_factor: 0.95        # 衰减因子
  enable_source_weighting: true # 启用源权重
  source_weights:           # 源权重
    reuters.com: 1.0
    bloomberg.com: 1.0
    coindesk.com: 0.9
    cointelegraph.com: 0.8
    default: 0.5

# 性能配置
performance:
  batch_processing: true     # 批处理
  batch_size: 50            # 批处理大小
  max_processing_time: 10.0  # 最大处理时间（秒）
  enable_parallel: true      # 启用并行处理
  max_workers: 4            # 最大工作线程数

# 监控配置
monitoring:
  enable_metrics: true       # 启用指标收集
  metrics_interval: 60      # 指标收集间隔（秒）
  log_duplicate_stats: true  # 记录重复统计
  enable_performance_alerts: true # 启用性能告警

# 自定义规则
custom_rules:
  enabled: false            # 启用自定义规则
  rules_path: rules/deduplication_rules.json # 规则路径
  rule_evaluation_order: ["content", "title", "semantic", "time"] # 规则评估顺序