# 做空分析师代理配置文件

# 核心配置
core:
  # 性能设置
  max_concurrent_requests: 1000
  target_latency_ms: 2000
  cache_ttl_seconds: 300

  # 分析模块开关
  enable_technical_analysis: true
  enable_sentiment_analysis: true
  enable_llm_analysis: true
  enable_risk_management: true

  # 做空专用设置
  min_signal_strength: 0.7
  max_risk_level: 3
  enable_short_squeeze_detection: true
  liquidity_threshold: 0.8

  # LLM分析设置
  llm_model_provider: "openai"
  llm_temperature: 0.3
  max_analysis_tokens: 2000

  # 风险控制设置
  max_position_size_ratio: 0.1
  stop_loss_multiplier: 1.5
  enable_dynamic_hedging: true

# 数据库配置
database:
  host: "localhost"
  port: 5432
  database: "crypto_trading"
  username: "postgres"
  password: ""
  pool_size: 10
  max_overflow: 20

# Redis配置
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  max_connections: 100
  socket_timeout: 5

# LLM配置
llm:
  provider: "openai"
  model: "gpt-4"
  api_key: ""
  base_url: null
  max_tokens: 2000
  temperature: 0.3
  timeout: 30
  max_retries: 3

# 交易所配置
exchanges:
  binance:
    api_key: ""
    secret: ""
    passphrase: null
    sandbox: true
    rate_limit: 100
    timeout: 10

  bybit:
    api_key: ""
    secret: ""
    passphrase: null
    sandbox: true
    rate_limit: 100
    timeout: 10

# 技术指标配置
indicators:
  # 移动平均线交叉指标
  ma_crossover:
    fast_period: 5
    slow_period: 20
    signal_threshold: 0.02

  # MACD背离指标
  macd_divergence:
    fast_period: 12
    slow_period: 26
    signal_period: 9
    lookback_period: 5

  # RSI超买指标
  rsi_overbought:
    period: 14
    overbought_threshold: 70
    oversold_threshold: 30

  # 布林带上轨指标
  bb_upper:
    period: 20
    std_dev: 2

  # 量价背离指标
  volume_divergence:
    lookback_period: 5

# 智能信号识别配置
signal_recognition:
  # 信号融合方法 (weighted_sum, consensus, hierarchical)
  fusion_method: "weighted_sum"

  # 指标权重配置
  indicator_weights:
    MA_CROSSOVER: 0.25
    RSI_OVERBOUGHT: 0.20
    BOLLINGER_UPPER: 0.20
    VOLUME_DIVERGENCE: 0.15
    MACD_DIVERGENCE: 0.20

  # 信号过滤阈值
  min_confidence_threshold: 0.7
  min_supporting_indicators: 2
  max_conflicting_indicators: 1

  # 时间窗口配置 (秒)
  signal_time_window: 300      # 5分钟
  historical_window: 86400     # 24小时

  # 风险评估权重
  risk_weights:
    market_volatility: 0.3
    signal_consistency: 0.4
    technical_confirmation: 0.3

  # 分层融合配置
  hierarchy_levels:
    primary: ["MA_CROSSOVER", "RSI_OVERBOUGHT"]
    secondary: ["BOLLINGER_UPPER", "MACD_DIVERGENCE"]
    confirmatory: ["VOLUME_DIVERGENCE"]

# LLM分析配置
llm_analysis:
  # LLM提供商设置
  provider: "mock"              # openai, anthropic, local, mock
  model: "gpt-4"               # 模型名称
  api_key: ""                  # API密钥
  base_url: null               # 自定义API地址

  # 分析参数
  max_tokens: 2000             # 最大token数
  temperature: 0.3             # 创造性参数
  top_p: 0.9                  # 核心采样
  frequency_penalty: 0.0      # 频率惩罚
  presence_penalty: 0.0       # 存在惩罚

  # 性能优化
  enable_cache: true           # 启用缓存
  cache_ttl: 300               # 缓存TTL（秒）
  enable_context: true        # 启用上下文管理
  max_context_size: 100        # 最大上下文大小
  enable_batch: true          # 启用批量处理

  # 分析质量控制
  min_confidence_threshold: 0.6  # 最小置信度阈值
  enable_validation: true       # 启用结果验证
  enable_fallback: true        # 启用回退机制

  # 成本控制
  max_monthly_cost: 100.0      # 月度成本限制
  cost_per_1k_tokens: 0.002   # 每1k token成本
  enable_cost_monitoring: true # 启用成本监控

# 监控配置
monitoring:
  enable_metrics: true
  metrics_port: 8000
  log_level: "INFO"
  log_file: "logs/short_analyst.log"
  enable_tracing: true
  tracing_sample_rate: 0.1

# 其他配置
environment: "development"
debug: false
config_version: "1.0.0"